# Generated by Django 5.2.7 on 2025-10-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('trigger_type', models.CharField(choices=[('on_signup', 'On Signup'), ('after_1_day', 'After 1 Day'), ('button_click', 'On Button Click')], max_length=50)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
