# Generated by Django 5.2.7 on 2025-10-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailplans', '0002_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='rendered_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailplan',
            name='template_vars',
            field=models.JSONField(blank=True, default=dict, help_text='Merge variables, e.g. {"first_name": "Rispa"}'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='mailplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='mailplan',
            name='recipient_email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='mailplan',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed'), ('paused', 'Paused')], db_index=True, default='active', max_length=20),
        ),
    ]
