# Generated by Django 5.2.7 on 2025-10-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailplans', '0003_emaillog_rendered_body_mailplan_template_vars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailplan',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
