# Generated by Django 5.2.7 on 2025-10-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailplans', '0004_mailplan_recipient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailplan',
            name='flow',
            field=models.JSONField(blank=True, default=dict, help_text='Visual flow JSON: {nodes: [], edges: []}'),
        ),
    ]
