# Generated by Django 5.2.7 on 2025-10-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailplans', '0005_mailplan_flow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailplan',
            name='content',
        ),
        migrations.RemoveField(
            model_name='mailplan',
            name='recipient_email',
        ),
        migrations.RemoveField(
            model_name='mailplan',
            name='recipient_name',
        ),
        migrations.RemoveField(
            model_name='mailplan',
            name='subject',
        ),
        migrations.AddField(
            model_name='mailplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mailplan',
            name='flow',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='mailplan',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mailplan',
            name='template_vars',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='mailplan',
            name='trigger_type',
            field=models.CharField(choices=[('on_signup', 'On Signup'), ('after_1_day', 'After 1 Day'), ('button_click', 'On Button Click')], default='on_signup', max_length=50),
        ),
    ]
