# Generated by Django 5.2.7 on 2025-10-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailplans', '0006_remove_mailplan_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailplan',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mailplan',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='mailplan',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='mailplan',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mailplan',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mailplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mailplan',
            name='flow',
            field=models.JSONField(blank=True, default=dict, help_text='Visual flow JSON: {nodes: [], edges: []}'),
        ),
        migrations.AlterField(
            model_name='mailplan',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mailplan',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed'), ('paused', 'Paused')], default='active', max_length=20),
        ),
    ]
