# Generated by Django 5.2.7 on 2025-10-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailplans', '0007_remove_mailplan_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailplan',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
